ListenAndWrite.Web/Models/AudioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ListenAndWrite.Web.Models
{
    public class AudioViewModel
    {
        public int Id { set; get; }
        public string AudioTitle { set; get; }
        public string Path { set; get; }
        public int Level { set; get; }
        public int Duration { set; get; }
        public int NumTrack { set; get; }
        public string Description { set; get; }
        public string CreatedBy { set; get; }
        public DateTime CreatedDate { set; get; }
        public string UpdateBy { set; get; }
        public DateTime? UpdateDate { set; get; }
        public bool Status { set; get; }
        public virtual IEnumerable<TrackViewModel> Tracks { set; get; }
        public virtual IEnumerable<ScoreViewModel> Scores { set; get; }
    }
}

ListenAndWrite.Web/Controllers/AudioController.cs
using AutoMapper;
using ListenAndWrite.Model.Models;
using ListenAndWrite.Service;
using ListenAndWrite.Web.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ListenAndWrite.Web.Controllers
{
    public class AudioController : Controller
    {
        private IAudioService _audioService;

        public AudioController(IAudioService audioService)
        {
            this._audioService = audioService;
        }

        public ActionResult Level(int? level)
        {
            var listLevel = _audioService.GetListLevel();
            if (level != null)
                ViewBag.Level = level;
            return View(listLevel);
        }

        public ActionResult Choose(int id)
        {
            var audioModel = _audioService.GetById(id);
            audioModel.NumTrack = _audioService.GetTotalTrack(id);
            var audioViewModel = Mapper.Map<Audio, AudioViewModel>(audioModel);
            return View(audioViewModel);
        }

        [HttpGet]
        public JsonResult LoadAudio(int page, int pageSize, int? level,string search)
        {
            int totalRow = 0;
            var audioModel = _audioService.GetLastestActiveAudio(search,level, page, pageSize, out totalRow);
            var audioViewModel = Mapper.Map<IEnumerable<Audio>, IEnumerable<AudioViewModel>>(audioModel);
            return Json(new
            {
                Items = audioViewModel,
                TotalCount = totalRow,
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

ListenAndWrite.Web/Views/Audio/AddAudio.cshtml
@model ListenAndWrite.Web.Models.AudioViewModel
@{
    ViewBag.Title = "AddAudio";
    Layout = "~/Views/Shared/AdminLayouts.cshtml";
}
@section footerJS{
    <script>
        $('#btnSelectAudio').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder;
            finder.selectActionFunction = function (url) {
                $('#txtAudio').val(url);
            }
            finder.popup();
        });
    </script>
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Thêm mới audio
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Trang chủ</a></li>
        <li><a href="#">Audio</a></li>
        <li><a ui-sref="#">Audio</a></li>
        <li class="active">Thêm mới</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Thêm mới</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        @using (Html.BeginForm("AddAudio", "Audio", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken();
            @Html.ValidationSummary(false, "", new { @class = "error" })
            <div class="box-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Audio Title</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.AudioTitle, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Audio Path</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Path, new { @class = "form-control", @id = "txtAudio" })
                        <button id="btnSelectAudio" class="btn btn-default">Upload file</button>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Level</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Level, new { @class = "form-control", type = "number", min = "1", step = "1" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Duration</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Duration, new { @class = "form-control", type = "number", min = "0", step = "1" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                @Html.CheckBoxFor(model => model.Status)
                                Kích hoạt
                            </label>
                        </div>

                    </div>
                </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a href="/Admin/ListAudio" class="btn btn-default">Hủy</a>
                <button type="submit" class="btn btn-info pull-right">Lưu</button>
            </div>

        }

    </div>
    <!-- /.box -->
</section>
<!-- /.content -->

ListenAndWrite.Web/Views/Audio/Choose.cshtml
@model ListenAndWrite.Web.Models.AudioViewModel
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Choose";
    Layout = "~/Views/Shared/Layouts.cshtml";
}
@section footerJS{
    <script src="~/Assets/Admin/libs/jquery-ui/jquery-ui.js"></script>
    <link href="~/Assets/Admin/libs/jquery-ui/themes/base/jquery-ui.css" rel="stylesheet" />
    <script src="~/Assets/Client/js/canvasjs.min.js"></script>
    <script src="~/Assets/Client/js/controllers/playAudio.js"></script>
}
<div class="row" data-sticky_parent>
    <div class="col-lg-8 content-wrapper">
        <div data-sticky_column>
            <div class="m-post-content m-post-content--tok">
                <div class="post-top">
                    
                    <h1 class="post-title">
                        <table>
                            <tr>
                                <td>
                                    <div style="width:120px;height:120px; border: 6px solid #DDDDDD; background:RGB(120,188,100);vertical-align:middle;">
                                        <center style="padding:10px;"><a href="#" style="color: #000000;background-color: RGB(120,188,100);">Level @Model.Level</a></center>
                                    </div>
                                </td>
                                <td>
                                    @Model.AudioTitle
                                </td>
                            </tr>
                        </table>
                    </h1>
                    @*<div class="post-meta">
                            <div class="item">
                                <i class="fa fa-microphone"></i>
                                <strong>English</strong>
                            </div>
                            <div class="item">
                                <i class="fa fa-address-book-o"></i> <a href="https://www.listen-and-write.com/channel/user/dFpvNkVmOG05eU1uUGx3MDJ3bE1oVXdOd3h2WGxzZzA2M3FiSVpOclAraz0tLURQWUN0M1QwazR2WE8xbnVaQmFyWFE9PQ==--bda5df74f1bdd15535646f4e5e8f21b626a2dde5">listen***</a>
                            </div>
                            <div class="item">
                                <i class="fa fa-clock-o"></i>
                                on 2018/08/13
                            </div>
                        </div>*@
                </div>
                <div class="entry-content">
                    <div id="player2" style="border:2px solid #dddddd; padding-bottom:10px;">
                        <p>
                            <div id="sentence_list">

                                <div>
                                    <i style="padding: 0px 15px;">@ListenAndWrite.Web.Resources.HomeTexts.Track</i> : <input id="btn-prev" type=button value="<" class="btn-prev" />
                                    <span id="currentTrack">1</span>
                                    of <span id="numTrack">@Model.NumTrack</span>
                                    <input id="btn-next" type=button value=">" class="btn-next" />
                                </div>
                                <div>
                                    <br />
                                    <table border="0">
                                        <tr>
                                            <td width="20" align=right></td>
                                            <td>
                                                <div style="overflow: hidden;position: relative;height:80px;">
                                                    <div id="slimprogress" style="width:517px; height:3px;"></div>
                                                    <input type="hidden" id="audioId" value="@Model.Id" />
                                                    <div>
                                                        <audio controls id="audio" hidden="hidden" src="@Model.Path" type="audio/mpeg"></audio>
                                                    </div>
                                                    <div class="form-group text-center">
                                                        <button class="btn btn-primary btn-lg" id="btn-play">
                                                            <span class="glyphicon glyphicon-play"></span>@ListenAndWrite.Web.Resources.HomeTexts.Play
                                                        </button>
                                                        <div class="btn btn-primary btn-lg btn-next" id="btn-next2">
                                                            <span class="glyphicon glyphicon-plus"></span> @ListenAndWrite.Web.Resources.HomeTexts.NextTrack
                                                        </div>
                                                        <button class="btn btn-primary btn-lg" id="btn-score">
                                                            <span class="glyphicon glyphicon-certificate"></span><span style="color: white">@ListenAndWrite.Web.Resources.HomeTexts.FinalScore</span>
                                                        </button>
                                                        <h2 id="totalScore" style="color:red;"></h2>
                                                    </div>

                                                </div>
                                                <i class='button medium icon'><i class='delete'></i><button type='button' id="stop">@ListenAndWrite.Web.Resources.HomeTexts.Pause</button></i>
                                                <i class='button medium icon'><i class='check'></i><button id="hint" type='button'>@ListenAndWrite.Web.Resources.HomeTexts.Hint</button></i>
                                                <span id="hintword" style="font-size:16px;font-weight:bold;color:blue;"></span>
                                                <div><textarea cols="38" rows="1" id="audioScript" style=""></textarea></div>
                                                <div>
                                                    <button id="submit" class="btn-success">@ListenAndWrite.Web.Resources.HomeTexts.Submit</button>
                                                </div>
                        <p id="result"></p>
                        @if (Request.IsAuthenticated)
                        {
                            <input type="hidden" id="userId" value="@User.Identity.GetUserId()" />
                            <div id="chartContainer" style="height: 300px; width: 100%;"></div>
                        }
                        else
                        {
                            <h1 id="totalPoint"></h1>
                            <center>
                                <br />
                                <h3>
                                    @ListenAndWrite.Web.Resources.HomeTexts.PleaseLogin . >>
                                    <a href="/Account/Login/">@ListenAndWrite.Web.Resources.HomeTexts.Login</a>
                                </h3>
                                <image src="https://www.listen-and-write.com/images/sample_scores2.png" alt="sample scores">
                            </center>
                        }

                        <div>
                            <span id="keylog" style="width:500px; height:100px; display:none">
                                <span id="key_a">A</span>
                                <span id="key_b">B</span>
                                <span id="key_c">C</span>
                                <span id="key_d">D</span>
                                <span id="key_e">E</span>
                                <span id="key_f">F</span>
                                <span id="key_g">G</span>
                                <span id="key_h">H</span>
                                <span id="key_i">I</span>
                                <span id="key_j">J</span>
                                <span id="key_k">K</span>
                                <span id="key_l">L</span>
                                <span id="key_m">M</span>
                                <span id="key_n">N</span>
                                <span id="key_o">O</span>
                                <span id="key_p">P</span>
                                <span id="key_q">Q</span>
                                <span id="key_r">R</span>
                                <span id="key_s">S</span>
                                <span id="key_t">T</span>
                                <span id="key_u">U</span>
                                <span id="key_v">V</span>
                                <span id="key_w">W</span>
                                <span id="key_x">X</span>
                                <span id="key_y">Y</span>
                                <span id="key_z">Z</span>
                            </span>
                        </div>
                        <br />
                        <div id="logger"></div>
                        </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                        </tr>
                        </table>
                    </div>
                </div>
                </p>
            </div>
        </div>  <!-- player2 -->
        <div class='command' style='width:100%;'>
            &nbsp;<strong>Écouter et écrire</strong><br />
            <ul id="failedWord" style='display:inline-block;'></ul>
        </div>

        <p>



        </p>
        <div id="myavgscore" style="font-weight: bold; font-size: 1.3em;"></div><br />
        <div id="myscore"></div>
        

    </div>
</div>
    </div>
</div>
<div class="col-lg-4 sidebar sidebar--right u-md-down-margin-t-40">
    <div class="sidebar__inner">
        <div class="widget widget--transparent-box img-banner">
            <figure>


            </figure>

            <!-- display  -->

        </div>
        <!-- trending news -->
        @*<div class="widget widget--border-box cat-trending single-cat">
            <div class="widget__title has-ajax-load">
                <h4>Related Audios ... Level 11 <i class="fa fa-star-half-o"></i></h4>
            </div>
            <ul class="posts-wrap">
                <li class="cat-sports">
                    <div class="post-content">
                        <h6 class="post-title">
                            <a href="https://www.listen-and-write.com/audio/show/16559">Software Teaches Robot Hand How to Move in the Real World</a>
                        </h6>
                        <div class="post-meta">
                            <i class="fa fa-clock-o"></i> on 2018/08/06
                        </div>
                    </div>
                </li>
                <li class="cat-sports">
                    <div class="post-content">
                        <h6 class="post-title">
                            <a href="https://www.listen-and-write.com/audio/show/16552">One of English&#39;s Most Beautiful Words-VOA-Bach</a>
                        </h6>
                        <div class="post-meta">
                            <i class="fa fa-clock-o"></i> on 2018/08/04
                        </div>
                    </div>
                </li>
                <li class="cat-sports">
                    <div class="post-content">
                        <h6 class="post-title">
                            <a href="https://www.listen-and-write.com/audio/show/16423">Another Big Year for Largest Comic Book Event of its Kind</a>
                        </h6>
                        <div class="post-meta">
                            <i class="fa fa-clock-o"></i> on 2018/07/21
                        </div>
                    </div>
                </li>
                <li class="cat-sports">
                    <div class="post-content">

                    </div>
                </li>
            </ul>
        </div>*@
        <!-- banner -->
        <div class="widget widget--transparent-box img-banner">
            <figure>


            </figure>
        </div>
    </div>
</div>
<div id="dialog">
</div>
<div id="dialogFinish">
</div>

ListenAndWrite.Web/Views/Audio/Level.cshtml
@model IEnumerable<int>
@{
    ViewBag.Title = "Level";
    Layout = "~/Views/Shared/Layouts.cshtml";
}
@section footerJS{
    <script src="~/Assets/Admin/libs/mustache/mustache.min.js"></script>
    <script src="~/Assets/Client/js/jquery.twbsPagination.min.js"></script>
    <script src="~/Assets/Client/js/controllers/listAudio.js"></script>
    <script async src="~/Assets/Client/pagead2.googlesyndication.com/pagead/js/f.txt"></script>
    <!-- index middle text only -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:234px;height:60px"
         data-ad-client="ca-pub-0119806589085646"
         data-ad-slot="2273830705"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
}

<div class="row" data-sticky_parent="">
    <div class="col-lg-8 content-wrapper">
        <div class="posts-box3 archive-box">
            <div class="posts-box3__top">
                <h2 class="posts-box3__top__title">@ListenAndWrite.Web.Resources.HomeTexts.LatestAudio: @(ViewBag.Level != null ? " "+ @ListenAndWrite.Web.Resources.HomeTexts.Level+" " + ViewBag.Level : "") </h2>

            </div>
            <input type="hidden" id="level" value="@ViewBag.Level" />

            <div class="archive-posts">


            </div><!--//.posts-list -->
            <ul id="pagination" class="pagination-sm"></ul>
            @*<nav class="pagination" role="navigation" aria-label="pager">


                    <span class="page current">
                        1
                    </span>
                    <span class="page">
                        <a rel="next" href="level4658.html?page=2">2</a>
                    </span>
                    <span class="page">
                        <a href="level9ba9.html?page=3">3</a>
                    </span>
                    <span class="page">
                        <a href="levelfdb0.html?page=4">4</a>
                    </span>
                    <span class="page">
                        <a href="levelaf4d.html?page=5">5</a>
                    </span>
                    <span class="page gap">&hellip;</span>
                    <span class="next">
                        <a rel="next" href="level4658.html?page=2">Next &rsaquo;</a>
                    </span>
                    <span class="last">
                        <a href="levelaa9e.html?page=287">Last &raquo;</a>
                    </span>
                </nav>*@
        </div> <!--//.posts-box  -->
    </div>
    <div class="col-lg-4 sidebar sidebar--right u-md-down-margin-t-40">
        <div class="sidebar__inner" data-sticky_column="">
            <div class="widget widget--transparent-box img-banner">
                <figure>
                    <div class="m-post-content m-post-content--nyc">
                        <b>@ListenAndWrite.Web.Resources.HomeTexts.Level</b>
                        <div class="post-tags">
                            <div class="tags-wrap">
                                @foreach (var level in Model)
                                {
                                    <a style="font-size: 80%;" href="/audio/level/@(level)">@(level)</a>
                                }

                            </div>
                        </div>
                    </div>
                </figure>
            </div>
            <div class="widget widget--transparent-box img-banner">
                <figure>

                </figure>
            </div>

        </div>
    </div>
</div>
<script id="data-template" type="x-tmpl-mustache">
    <article class="post-item">
        <div class="post-content">
            <div class="post-meta">
                <h6 class="post-title">
                    <a href="/audio/choose/{{Id}}">{{AudioTitle}}</a>
                </h6>
                <div class="item">
                </div>
                <div class="item">
                    <i class="fa fa-star-half-o"></i>level = {{Level}}
                </div>
                <div class="item">
                    <i class="fa fa-hourglass-o"></i>{{Duration}}
                </div>
                <div class="item">
                    <time><i class="fa fa-clock-o"></i>{{CreatedDate}}</time>
                </div>
            </div>
        </div>
    </article>
    <hr />
</script>